# Get base image
FROM debian:buster

# Get necessary applications
RUN set -ex; \
	apt-get update; \
	apt-get -y install wget curl vim \
		mariadb-server; \
	# Remove apt-get caches
	rm -rf /var/lib/apt/lists;

# Copy shell script
COPY tools/init.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/init.sh

# Copy my.cnf into container
COPY conf/my.cnf /etc/

# comment out a few problematic configuration values
RUN	find /etc/mysql/ -name '*.cnf' -print0 \
	| xargs -0 grep -lZE '^(bind-address|log|user\s)' \
	| xargs -rt -0 sed -Ei 's/^(bind-address|log|user\s)/#&/';

# uncomment port related directives
# RUN	find /etc/mysql/ -name '*.cnf' -print0 \
# 	| xargs -rt -0 sed -Ei '/^#port/s/^#//g';

# Change owner of all files in the html directory
# /etc/mysql/mariadb.conf.d

# purge and re-create /var/lib/mysql with appropriate ownership

RUN set -ex; \
	rm -rf /var/lib/mysql; \
	mkdir -p /var/lib/mysql /var/run/mysqld; \
	chown -R mysql:mysql /var/lib/mysql /var/run/mysqld; \
	chmod 777 /var/run/mysqld;
	# find /etc/mysql/ -name '*.cnf' -print0 \
	# | xargs -0 grep -lZE '^(bind-address|log|user\s)' \
	# | xargs -rt -0 sed -Ei 's/^(bind-address|log|user\s)/#&/';


EXPOSE 3306

# Keep running the container
# CMD ["bash", "/tmp/share/init.sh"]
# CMD ["tail", "-f", "/dev/null"]
CMD ["/usr/local/bin/init.sh"]
