{
 "title": "Wordpress statistics dashboard",
 "description": "Wordpress statistics dashboard includes:\n - Top 5 pages\n - Top browsers\n - Top 10 Referring Sites\n - Top Engines\n - Total Visitors \n - Total Online Users\n - Total Visits\n - Top 10 Countries (Count Visitor)\n - Top 10 Countries (Hits)\n - Visit & Visitor in the last 10 days\n",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Top 5 Pages",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT b.post_title as 'Post Title', sum(a.count) as Visits \nFROM wp_statistics_pages a, wp_posts b \nwhere a.id=b.ID \ngroup by a.id \norder by Visits desc\nlimit 5;"
    }
   ]
  },
  {
   "title": "Top Browsers",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select now() AS \"time\", \ncase \nwhen agent like 'Chrome' then 'Chrome'\nwhen agent like 'FireFox' then 'FireFox'\nwhen agent like 'Safari' then 'Safari'\nwhen agent like 'Samsung Internet' then 'Samsung Internet'\nwhen agent like 'Unknown' then 'Other'\nend\nagent, count(*) FROM wp_statistics_visitor\nwhere agent in ('Chrome', 'FireFox', 'Safari', 'Samsung Internet', 'Unknown') group by agent;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) as 'Total Visitor' FROM wp_statistics_visitor;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(visit) as 'Total Visits' FROM wp_statistics_visit order by last_visit desc limit 15;\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) as 'Online Users' FROM wp_statistics_useronline;"
    }
   ]
  },
  {
   "title": "Top 10 Referring Sites",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(referred, '/', 3), '://', -1), '/', 1), '?', 1),'www.',-1)\n AS Domain,\n count(*) AS 'References Hits' \n FROM wp_statistics_visitor\n group by domain order by 'References Hits' desc limit 10;"
    }
   ]
  },
  {
   "title": "Visit & Visitor in the last 10 days",
   "type": "graph",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  last_visit AS \"time\",\n  Visit\nFROM wp_statistics_visit\nWHERE\n  $__timeFilter(last_visit)\nORDER BY last_visit"
    },
    {
     "rawSql": "SELECT DATE(last_counter) as time, count(*) as Visitor FROM wp_statistics_visitor group by last_counter;"
    }
   ]
  }
 ]
}